# Generated by Django 2.2.6 on 2019-11-13 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=12)),
                ('pwd', models.CharField(max_length=150)),
                ('cpwd', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('dates', models.DateField(default=datetime.datetime.now)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicformapp.category')),
                ('name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='basicformapp.users')),
            ],
        ),
    ]
