# Generated by Django 2.2.6 on 2019-11-14 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicformapp', '0002_remove_users_cpwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicformapp.users'),
        ),
    ]
