# Generated by Django 2.1 on 2019-11-08 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student.Batch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ForeignKey(default='P2', on_delete=django.db.models.deletion.CASCADE, to='student.Course'),
            preserve_default=False,
        ),
    ]
