# Generated by Django 2.2.3 on 2019-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('addr', models.CharField(max_length=120)),
                ('mob', models.IntegerField(max_length=10)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
