# Generated by Django 2.1 on 2019-10-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='total',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(default='cse', max_length=20),
            preserve_default=False,
        ),
    ]
